do $$ begin if not exists(select 1 from pg_roles where rolname=$q$anon$q$) then create role anon nologin; end if; if not exists(select 1 from pg_roles where rolname=$q$authenticated$q$) then create role authenticated nologin; end if; end $$;
create schema auth; create table auth.users(id uuid primary key);
create or replace function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$;
create schema storage;
create table storage.buckets(id text primary key, name text, public boolean);
create table storage.objects(id uuid default gen_random_uuid() primary key, bucket_id text, name text);
alter table storage.objects enable row level security;
create or replace function storage.foldername(n text) returns text[] language sql as $$ select string_to_array(n,'/') $$;
create publication supabase_realtime;
grant usage on schema public, auth, storage to anon, authenticated;
